# fly.toml app configuration file generated for withered-snowflake-3299 on 2023-05-05T11:25:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-snowflake-3299"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
