# fly.toml app configuration file generated for weathered-field-7447 on 2023-05-01T20:29:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-field-7447"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
